### ISSUE TITLE
Mistake in Readme Documentation

### ISSUE THREAD

**Issue by MichaelOVertolli** [OfficeDev/Outlook-SDK-Android#9]
The readme for the git lists this code:

`@Override
                    public void onSuccess(final AuthenticationResult authenticationResult) {
                        if (authenticationResult != null
                                && authenticationResult.getStatus() == AuthenticationStatus.Succeeded) {
                            mResolver = new DependencyResolver.Builder(
                                            new OkHttpTransport(), new GsonSerializer(),
                                            new AuthenticationCredentials() {
                                            @Override
                                            public Credentials getCredentials() {
                                                return new OAuthCredentials(token);
                                            }
                                        }).build();
                            result.set(true);
                        }
                    }`

The line `return new OAuthCredentials(token)` does not explain what token is.

I'm assuming it _should_ be `return new OAuthCredentials(authenticationResult.getAccessToken())`

**Comment by lindalu-MSFT** [comment]
Fixed
